# Generated by Django 5.0.10 on 2025-09-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('company', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patient', '0008_alter_nextofkin_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmode',
            old_name='paymet_mode',
            new_name='payment_mode',
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='payment_category',
            field=models.CharField(choices=[('cash', 'Cash'), ('insurance', 'Insurance'), ('mpesa', 'MPesa'), ('cheque', 'CHEQUE'), ('direct_to_bank', 'DIRECT_TO_BANK')], default='cash', max_length=20),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='billing_inv_status_541249_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='billing_inv_invoice_2a056e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient'], name='billing_inv_patient_a03932_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['status'], name='billing_inv_status_070f48_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='billing_inv_invoice_563f13_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['payment_mode'], name='billing_inv_payment_f41c38_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['item_created_at'], name='billing_inv_item_cr_b5c90c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmode',
            index=models.Index(fields=['payment_category'], name='billing_pay_payment_045d4a_idx'),
        ),
    ]
