# Generated by Django 5.0.10 on 2025-10-23 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_paymet_mode_paymentmode_payment_mode_and_more'),
        ('patient', '0008_alter_nextofkin_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.paymentmode')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.invoiceitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.paymentreceipt')),
            ],
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['created_at'], name='billing_pay_created_2ab960_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['patient'], name='billing_pay_patient_7e7e45_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['applied_at'], name='billing_pay_applied_45deb4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['invoice_item'], name='billing_pay_invoice_51528d_idx'),
        ),
    ]
