# Generated by Django 5.0.10 on 2025-10-26 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoicepayment_reference_number_paymentreceipt_and_more'),
        ('company', '0001_initial'),
        ('patient', '0008_alter_nextofkin_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.insurancecompany'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['insurance'], name='billing_pay_insuran_15613b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['payment_date'], name='billing_pay_payment_3ead7c_idx'),
        ),
    ]
