# Generated by Django 5.0.10 on 2026-01-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_paymentreceipt_insurance_paymentreceipt_payment_date_and_more'),
        ('company', '0002_company_patient_id_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmode',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default payment mode for cash payments'),
        ),
        migrations.AddIndex(
            model_name='paymentmode',
            index=models.Index(fields=['is_default'], name='billing_pay_is_defa_29cbc5_idx'),
        ),
    ]
