# Generated by Django 5.0.10 on 2026-03-11 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_update_payment_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_account', to='billing.paymentmode')),
            ],
        ),
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_bal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('min_bal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_bal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('min_trans', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_trans', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subaccounts', to='billing.mainaccount')),
            ],
        ),
    ]
