# Generated by Django 5.0.10 on 2026-03-11 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_mainaccount_subaccount'),
        ('inventory', '0010_merge_20260301_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='source_tag',
            field=models.ForeignKey(blank=True, help_text='Used for departmental revenue tracking (e.g. Lab, Pharmacy, Main)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department'),
        ),
    ]
