# Generated by Django 5.0.10 on 2026-03-16 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoiceitem_source_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainaccount',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='subaccount',
            name='payment_mode',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_account', to='billing.paymentmode'),
        ),
    ]
