# Generated by Django 5.0.10 on 2026-03-16 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_remove_mainaccount_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccount',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='billing.paymentmode'),
        ),
    ]
