# Generated by Django 5.0.10 on 2026-03-16 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_subaccount_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='sub_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='billing.subaccount'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.paymentmode'),
        ),
    ]
