# Generated by Django 5.0.10 on 2025-11-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='patient_id_prefix',
            field=models.CharField(blank=True, help_text='Prefix for patient IDs (e.g., ESMED-)', max_length=20, null=True),
        ),
    ]
