# For active development, use the following Dockerfile
FROM node:22.11.0-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# Copy package files separately to leverage cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]