# For active development, use the following Dockerfile
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Create a volume for node_modules so it doesn't get overridden by bind mount
VOLUME ["/app/node_modules"]
# RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "dev"]