# Generated by Django 5.0.10 on 2025-10-30 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_paymentreceipt_insurance_paymentreceipt_payment_date_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.paymentmode')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='inventory.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='inventory.supplierinvoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.supplierpaymentreceipt')),
            ],
        ),
        migrations.AddIndex(
            model_name='supplierpaymentreceipt',
            index=models.Index(fields=['created_at'], name='inventory_s_created_896969_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentreceipt',
            index=models.Index(fields=['supplier'], name='inventory_s_supplie_67d2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentreceipt',
            index=models.Index(fields=['payment_date'], name='inventory_s_payment_9e6b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentallocation',
            index=models.Index(fields=['applied_at'], name='inventory_s_applied_1e3677_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentallocation',
            index=models.Index(fields=['supplier_invoice'], name='inventory_s_supplie_f5dbab_idx'),
        ),
    ]
