# Generated by Django 5.0.10 on 2025-12-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplierpaymentreceipt_supplierpaymentallocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='units_of_measure',
            field=models.CharField(choices=[('unit', 'Unit'), ('kits', 'Kits'), ('mg', 'Milligram'), ('g', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Milliliter'), ('L', 'Liter')], max_length=255),
        ),
    ]
