# Generated by Django 5.0.10 on 2026-02-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_patient_id_prefix'),
        ('inventory', '0003_alter_item_units_of_measure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceitemsaleprice',
            options={'verbose_name': 'Insurance Item Sale Price', 'verbose_name_plural': 'Insurance Item Sale Prices'},
        ),
        migrations.AlterUniqueTogether(
            name='insuranceitemsaleprice',
            unique_together={('item', 'insurance_company')},
        ),
    ]
