# Generated by Django 5.0.10 on 2026-02-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('mass', 'Mass / Weight'), ('volume', 'Volume'), ('length', 'Length'), ('concentration', 'Concentration'), ('hematology', 'Hematology'), ('enzyme', 'Enzyme Activity'), ('hormone', 'Hormones & Tumor Markers'), ('microbiology', 'Microbiology'), ('urinalysis', 'Urinalysis'), ('coagulation', 'Coagulation'), ('blood_gas', 'Blood Gas'), ('osmolality', 'Osmolality & Density'), ('molecular', 'Molecular Biology'), ('dose', 'Dose & Ratio'), ('general', 'General')], default='general', max_length=30)),
            ],
            options={
                'ordering': ['category', 'symbol'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.unit'),
        ),
    ]
