# Generated by Django 5.0.10 on 2026-02-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_item_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'category', 'units_of_measure')},
        ),
    ]
