# Generated by Django 5.0.10 on 2026-02-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_seed_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('unit', 'Unit'), ('kits', 'Kits'), ('mg', 'Milligram'), ('g', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Milliliter'), ('L', 'Liter')], default='', max_length=255),
        ),
    ]
