# Generated by Django 5.0.10 on 2026-02-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_item_units_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lab_test_item',
            field=models.OneToOneField(blank=True, help_text='Auto-created Lab Test billing item paired to this Lab Reagent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagent_item', to='inventory.item'),
        ),
    ]
