# Generated by Django 5.0.10 on 2026-03-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_unique_together'),
        ('inventory', '0009_item_lab_test_item'),
    ]

    operations = [
    ]
