# Generated by Django 5.0.10 on 2026-03-16 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_paymentreceipt_sub_account_and_more'),
        ('inventory', '0010_merge_20260301_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpaymentreceipt',
            name='sub_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_receipts', to='billing.subaccount'),
        ),
        migrations.AlterField(
            model_name='supplierpaymentreceipt',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.paymentmode'),
        ),
    ]
