# Generated by Django 5.0.10 on 2026-03-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_merge_20260301_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='units_of_measure',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
