# Generated by Django 5.0.10 on 2026-03-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_item_units_of_measure'),
        ('inventory', '0011_supplierpaymentreceipt_sub_account_and_more'),
    ]

    operations = [
    ]
