# Generated by Django 5.0.10 on 2026-02-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('senior_nurse', 'Senior Nurse'), ('labtech', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('receptionist', 'Receptionist'), ('sysadmin', 'Sysadmin')], default='patient', max_length=20),
        ),
    ]
