# Generated by Django 5.0.10 on 2025-04-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('labtech', 'Lab Technician'), ('receptionist', 'Receptionist'), ('sysadmin', 'Sysadmin')], default='patient', max_length=20),
        ),
    ]
