# Generated by Django 5.0.10 on 2026-02-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_pharmacistprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customuser.customuser',),
        ),
    ]
