# Generated by Django 5.0.10 on 2025-03-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsample',
            name='patient_sample_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
