# Generated by Django 5.0.10 on 2025-12-06 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_alter_labtestrequest_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequestpanel',
            name='auto_interpretation',
            field=models.TextField(blank=True, help_text='Auto-generated interpretation based on result ranges', null=True),
        ),
        migrations.AddField(
            model_name='labtestrequestpanel',
            name='clinical_action',
            field=models.TextField(blank=True, help_text='Recommended clinical action from interpretation', null=True),
        ),
        migrations.AddField(
            model_name='labtestrequestpanel',
            name='requires_attention',
            field=models.BooleanField(default=False, help_text='Flagged for immediate attention'),
        ),
        migrations.CreateModel(
            name='LabTestInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_type', models.CharField(choices=[('critical_low', 'Critical Low'), ('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical_high', 'Critical High')], max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], default='B', max_length=1)),
                ('age_min', models.IntegerField(blank=True, help_text='Minimum age in years (leave blank for all ages)', null=True)),
                ('age_max', models.IntegerField(blank=True, help_text='Maximum age in years (leave blank for all ages)', null=True)),
                ('value_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum value for this range (leave blank for unbounded)', max_digits=10, null=True)),
                ('value_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum value for this range (leave blank for unbounded)', max_digits=10, null=True)),
                ('interpretation', models.TextField(help_text='Clinical interpretation for values in this range')),
                ('clinical_action', models.TextField(blank=True, help_text='Recommended clinical actions or follow-up', null=True)),
                ('requires_immediate_attention', models.BooleanField(default=False, help_text='Mark as requiring immediate clinical attention')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('lab_test_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='laboratory.labtestpanel')),
            ],
            options={
                'verbose_name': 'Lab Test Interpretation',
                'verbose_name_plural': 'Lab Test Interpretations',
                'ordering': ['lab_test_panel', 'sex', 'age_min', 'value_min'],
            },
        ),
    ]
