# Generated by Django 5.0.10 on 2025-12-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_units_of_measure'),
        ('laboratory', '0003_labtestrequestpanel_auto_interpretation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testkitcounter',
            options={'verbose_name': 'Reagent Test Counter', 'verbose_name_plural': 'Reagent Test Counters'},
        ),
        migrations.AddField(
            model_name='testkitcounter',
            name='available_tests',
            field=models.IntegerField(default=0, help_text='Total number of tests available across all kits in stock'),
        ),
        migrations.AddField(
            model_name='testkitcounter',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testkitcounter',
            name='minimum_threshold',
            field=models.IntegerField(default=10, help_text='Alert when available tests fall below this number'),
        ),
        migrations.AddField(
            model_name='testkitcounter',
            name='reagent_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'LabReagent'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_counter', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='testkitcounter',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='testkitcounter',
            name='lab_test_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.testkit'),
        ),
        migrations.CreateModel(
            name='TestPanelReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests_consumed_per_run', models.IntegerField(default=1, help_text='Number of tests consumed from this reagent per lab test run')),
                ('reagent_item', models.ForeignKey(limit_choices_to={'category': 'LabReagent'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('test_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_links', to='laboratory.labtestpanel')),
            ],
            options={
                'verbose_name': 'Test Panel Reagent',
                'verbose_name_plural': 'Test Panel Reagents',
                'unique_together': {('test_panel', 'reagent_item')},
            },
        ),
    ]
