# Generated by Django 5.0.10 on 2025-12-13 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_units_of_measure'),
        ('laboratory', '0004_alter_testkitcounter_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReagentConsumptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests_consumed', models.IntegerField(help_text='Number of tests consumed from reagent')),
                ('available_tests_before', models.IntegerField(help_text='Available tests before consumption')),
                ('available_tests_after', models.IntegerField(help_text='Available tests after consumption')),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('lab_test_request_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_consumptions', to='laboratory.labtestrequestpanel')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reagent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_logs', to='inventory.item')),
                ('test_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagent_consumptions', to='laboratory.labtestpanel')),
            ],
            options={
                'verbose_name': 'Reagent Consumption Log',
                'verbose_name_plural': 'Reagent Consumption Logs',
                'ordering': ['-consumed_at'],
                'indexes': [models.Index(fields=['reagent_item', '-consumed_at'], name='laboratory__reagent_e11d5b_idx'), models.Index(fields=['test_panel', '-consumed_at'], name='laboratory__test_pa_ad2edd_idx')],
            },
        ),
    ]
