# Generated by Django 5.0.10 on 2026-02-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_reagentconsumptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsample',
            name='collected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
