# Generated by Django 5.0.10 on 2026-02-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_unit_item_units'),
        ('laboratory', '0005_reagentconsumptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestpanel',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_panels', to='inventory.unit'),
        ),
    ]
