# Generated by Django 5.0.10 on 2026-02-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_patientsample_collected_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tat_minutes', models.PositiveIntegerField(default=60, help_text='Global default Turnaround Time in minutes if not specified per test panel')),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Settings',
                'verbose_name_plural': 'Lab Settings',
            },
        ),
    ]
