# Generated by Django 5.0.10 on 2026-03-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_labtestpanel_units'),
        ('laboratory', '0007_labsettings'),
    ]

    operations = [
    ]
