# Generated by Django 5.0.10 on 2026-03-01 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_merge_0006_labtestpanel_units_0007_labsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtestinterpretation',
            options={'ordering': ['test_profile'], 'verbose_name': 'Lab Test Interpretation', 'verbose_name_plural': 'Lab Test Interpretations'},
        ),
        migrations.RemoveField(
            model_name='labtestinterpretation',
            name='age_max',
        ),
        migrations.RemoveField(
            model_name='labtestinterpretation',
            name='age_min',
        ),
        migrations.RemoveField(
            model_name='labtestinterpretation',
            name='lab_test_panel',
        ),
        migrations.RemoveField(
            model_name='labtestinterpretation',
            name='range_type',
        ),
        migrations.RemoveField(
            model_name='labtestinterpretation',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='labtestinterpretation',
            name='value_max',
        ),
        migrations.RemoveField(
            model_name='labtestinterpretation',
            name='value_min',
        ),
        migrations.AddField(
            model_name='labtestinterpretation',
            name='test_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='laboratory.labtestprofile'),
        ),
        migrations.AlterField(
            model_name='labtestinterpretation',
            name='interpretation',
            field=models.TextField(help_text='Clinical interpretation for this test profile'),
        ),
    ]
