# Generated by Django 5.0.10 on 2026-03-04 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_alter_labtestinterpretation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='laboratory.archive')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='laboratory.archivecomponent')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='laboratory.archivesection')),
            ],
        ),
        migrations.CreateModel(
            name='PatientSampleArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archiving_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_expired', 'Not Expired'), ('expired', 'Expired')], default='not_expired', max_length=20)),
                ('action', models.CharField(blank=True, choices=[('dispose', 'Dispose'), ('retest', 'Retest')], max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient_sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive_record', to='laboratory.patientsample')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample_archive', to='laboratory.archiveposition')),
            ],
        ),
    ]
