# Generated by Django 5.0.10 on 2026-03-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_archive_archivecomponent_archivesection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='max_archive_duration',
            field=models.DurationField(blank=True, help_text='Maximum duration a specimen can be archived', null=True),
        ),
        migrations.AlterField(
            model_name='patientsamplearchive',
            name='action',
            field=models.CharField(blank=True, choices=[('dispose', 'Dispose'), ('retest', 'Retest'), ('released', 'Released')], max_length=20, null=True),
        ),
    ]
