# Generated by Django 5.0.10 on 2026-03-05 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_specimen_max_archive_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveposition',
            name='section',
        ),
        migrations.CreateModel(
            name='ArchiveRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='laboratory.archivesection')),
            ],
        ),
        migrations.AddField(
            model_name='archiveposition',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='laboratory.archiverack'),
        ),
    ]
