# Generated by Django 5.0.10 on 2026-03-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0012_remove_archiveposition_section_archiverack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsamplearchive',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='patientsamplearchive',
            name='status',
        ),
    ]
