# Generated by Django 5.0.10 on 2026-03-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0013_remove_expiry_date_status_from_patientsamplearchive'),
    ]

    operations = [
        migrations.RunSQL(
            # Convert existing interval values to integer days using EXTRACT
            sql="""
                ALTER TABLE laboratory_specimen
                ALTER COLUMN max_archive_duration TYPE integer
                USING EXTRACT(epoch FROM max_archive_duration)::integer / 86400;
            """,
            reverse_sql="""
                ALTER TABLE laboratory_specimen
                ALTER COLUMN max_archive_duration TYPE interval
                USING (max_archive_duration || ' days')::interval;
            """
        ),
        migrations.AlterField(
            model_name='specimen',
            name='max_archive_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum duration a specimen can be archived (in days)', null=True),
        ),
    ]
