# Generated by Django 5.0.10 on 2026-03-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0014_change_max_archive_duration_to_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='max_archive_duration',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Maximum duration a specimen can be archived (in days)', null=True),
        ),
    ]
