# Generated by Django 5.0.10 on 2026-03-05 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0015_specimen_max_archive_duration_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposedSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_sample_code', models.CharField(max_length=255)),
                ('position_name', models.CharField(max_length=255)),
                ('archiving_date', models.DateField()),
                ('disposed_on', models.DateField(auto_now_add=True)),
                ('disposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
