# Generated by Django 5.0.10 on 2026-03-07 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0017_add_retest_sample_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_sample_code', models.CharField(max_length=255)),
                ('facility_name', models.CharField(max_length=255)),
                ('receiving_lab_tech', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('released_on', models.DateTimeField(auto_now_add=True)),
                ('patient_sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_record', to='laboratory.patientsample')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_samples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
