# Generated by Django 5.0.10 on 2026-03-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0018_releasedsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencevalue',
            name='critical_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='referencevalue',
            name='critical_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
