# Generated by Django 5.0.10 on 2026-03-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0019_referencevalue_critical_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestpanel',
            name='unit',
        ),
    ]
