# Generated by Django 5.0.10 on 2025-08-01 05:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(choices=[('manual', 'Manual Hospital Bed'), ('semi_electric', 'Semi-Electric Hospital Bed'), ('fully_electric', 'Fully Electric Hospital Bed'), ('bariatric', 'Bariatric Hospital Bed')], default='manual', max_length=15)),
                ('bed_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ward_type', models.CharField(choices=[('general', 'General'), ('maternity', 'Maternity'), ('pediatrics', 'Pediatrics'), ('amenity', 'Amenity')], default='general', max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('reason_for_admission', models.TextField()),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_made', to=settings.AUTH_USER_MODEL)),
                ('attendance_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttendanceProcess', to='patient.attendanceprocess')),
                ('bed', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_patient', to='inpatient.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patient.patient')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='inpatient.ward')),
            ],
            options={
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InPatientTriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=45)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('pulse', models.PositiveIntegerField(null=True)),
                ('diastolic', models.PositiveIntegerField(null=True)),
                ('systolic', models.PositiveIntegerField(null=True)),
                ('bmi', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('patient_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triages', to='inpatient.patientadmission')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_types', models.CharField(choices=[('normal', 'Normal'), ('referral', 'External Referral'), ('deceased', 'Deceased')], default='normal')),
                ('discharged_at', models.DateTimeField(auto_now_add=True)),
                ('discharge_notes', models.TextField(blank=True, null=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='inpatient.patientadmission')),
                ('discharged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to='patient.referral')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='inpatient.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
        migrations.CreateModel(
            name='WardNurseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role': 'senior_nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.OneToOneField(limit_choices_to={'role': 'nurse'}, on_delete=django.db.models.deletion.CASCADE, related_name='ward_assignment', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_assignments', to='inpatient.ward')),
            ],
            options={
                'unique_together': {('nurse', 'ward')},
            },
        ),
    ]
