# Generated by Django 5.0.10 on 2025-08-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischarge',
            name='discharge_types',
            field=models.CharField(choices=[('normal', 'Normal'), ('referral', 'External Referral'), ('deceased', 'Deceased')], default='normal', max_length=20),
        ),
    ]
