# Generated by Django 5.0.10 on 2025-04-07 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharged_at', models.DateTimeField(auto_now_add=True)),
                ('discharge_notes', models.TextField(blank=True, null=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='inpatient.patientadmission')),
                ('discharged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
