# Generated by Django 5.0.10 on 2025-03-27 18:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
        ('inpatient', '0002_alter_patientadmission_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardNurseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_assignments_made', to='customuser.doctorprofile')),
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ward_assignment', to='customuser.nurseprofile')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_assignments', to='inpatient.ward')),
            ],
            options={
                'unique_together': {('nurse', 'ward')},
            },
        ),
    ]
