# Generated by Django 5.0.10 on 2026-02-01 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0002_alter_patientdischarge_discharge_types'),
        ('laboratory', '0005_reagentconsumptionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_test_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtestprofile')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_lab_tests', to='inpatient.schedule')),
            ],
        ),
    ]
