# Generated by Django 5.0.10 on 2026-02-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0003_scheduledlabtest'),
        ('laboratory', '0005_reagentconsumptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledlabtest',
            name='lab_test_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_occurrences', to='laboratory.labtestrequest'),
        ),
        migrations.AlterField(
            model_name='scheduledlabtest',
            name='lab_test_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtestprofile'),
        ),
    ]
