# Generated by Django 5.0.10 on 2025-03-28 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0003_wardnurseassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardnurseassignment',
            name='assigned_by',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wardnurseassignment',
            name='nurse',
            field=models.OneToOneField(limit_choices_to={'role': 'nurse'}, on_delete=django.db.models.deletion.CASCADE, related_name='ward_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
