# Generated by Django 5.0.10 on 2026-03-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0004_scheduledlabtest_lab_test_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatienttriage',
            name='spo2',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
