# Generated by Django 5.0.10 on 2025-09-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='note',
        ),
        migrations.AddField(
            model_name='consultation',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctors_note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='signs_and_symptoms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
