# Generated by Django 5.0.10 on 2025-08-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_triage_created_by_triage_created_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triage',
            name='created_by_user',
        ),
        migrations.AddField(
            model_name='triage',
            name='created_by',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
