# Generated by Django 5.0.10 on 2025-09-04 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_consultation_complaint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='email',
            new_name='provider_email_contact',
        ),
        migrations.AddField(
            model_name='referral',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='preferred_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
