# Generated by Django 5.0.10 on 2025-08-01 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_triage_created_by_triage_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triages', to='patient.patient'),
        ),
    ]
