# Generated by Django 5.0.10 on 2025-09-05 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_referral_reffered_doctor_referral_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='attendance_process',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='patient.attendanceprocess'),
        ),
    ]
