# Generated by Django 5.0.10 on 2025-09-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_referral_attendance_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='attendance_process',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_note', to='patient.attendanceprocess'),
        ),
    ]
