# Generated by Django 5.0.10 on 2025-09-07 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_consultation_attendance_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
