# Generated by Django 5.0.10 on 2025-09-22 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_referral_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='prescribeddrug',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_prescribed_drugs', to='patient.prescription'),
        ),
    ]
