# Generated by Django 5.0.10 on 2026-01-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_nextofkin_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctors_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='signs_and_symptoms',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
