# Generated by Django 5.0.10 on 2026-03-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_update_consultation_field_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='spo2',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
