# Generated by Django 5.0.10 on 2026-03-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_triage_spo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spo2_min', models.PositiveIntegerField(default=90)),
                ('spo2_warning_level', models.PositiveIntegerField(default=94)),
                ('systolic_min', models.PositiveIntegerField(default=90)),
                ('systolic_max', models.PositiveIntegerField(default=180)),
                ('diastolic_min', models.PositiveIntegerField(default=60)),
                ('diastolic_max', models.PositiveIntegerField(default=120)),
                ('temperature_min', models.DecimalField(decimal_places=2, default=35.0, max_digits=5)),
                ('temperature_max', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('pulse_min', models.PositiveIntegerField(default=40)),
                ('pulse_max', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
